# Generated by Django 3.2 on 2021-05-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='tweet_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='last_modified',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=200),
        ),
    ]
